### ISSUE TITLE
Single element namespace

### ISSUE THREAD

**Issue by erikcw** [steeni/reagent-bootstrap#1]
The use of `(ns reagent-boostrap...` is causing the clojurescript compiler to produce this warning:

```
WARNING: reagent-bootstrap is a single segment namespace at line 2 .lein-git-deps/reagent-bootstrap/src/reagent_bootstrap.cljs
```

This should be fixed by renaming the namespace, perhaps something like `(ns reagent-bootstrap.core)`?

**Comment by steeni** [comment]
Thanks,

I will see if I have time to fix this in the near future. Or you can make a pull request if you like. To be honest, I was a bit surprised that someone used this :). Any other suggestions and improvements are also appreciated.

**Comment by steeni** [comment]
And now it's closed. Thanks Erik.
